### ISSUE TITLE
DataTables arrows different from Windows to macOS

### ISSUE THREAD

**Issue by CodelineRed** [InsanityMeetsHH/file-sharing#2]
Current state:
![bildschirmfoto 2018-10-22 um 10 45 23](https://user-images.githubusercontent.com/35538671/47284480-cbe8e680-d5e7-11e8-90fa-b8adb4303c83.png)

Should be:
![bildschirmfoto 2018-10-22 um 10 48 46](https://user-images.githubusercontent.com/35538671/47284556-15d1cc80-d5e8-11e8-8971-c410c1e17c46.png)

Solution:
```css
table.dataTable thead .sorting:after, 
table.dataTable thead .sorting:before, 
table.dataTable thead .sorting_asc:after, 
table.dataTable thead .sorting_asc:before, 
table.dataTable thead .sorting_asc_disabled:after, 
table.dataTable thead .sorting_asc_disabled:before, 
table.dataTable thead .sorting_desc:after, 
table.dataTable thead .sorting_desc:before, 
table.dataTable thead .sorting_desc_disabled:after, 
table.dataTable thead .sorting_desc_disabled:before {
    font-family: Arial;
}
```
